
package com.ifmo.servicesclientlab1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeWebService", targetNamespace = "http://serviceslab1maven.ifmo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.ifmo.serviceslab1maven.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployees", targetNamespace = "http://serviceslab1maven.ifmo.com/", className = "com.ifmo.serviceslab1maven.GetEmployees")
    @ResponseWrapper(localName = "getEmployeesResponse", targetNamespace = "http://serviceslab1maven.ifmo.com/", className = "com.ifmo.serviceslab1maven.GetEmployeesResponse")
    public List<Employee> getEmployees();

    /**
     * 
     * @param city
     * @param surname
     * @param name
     * @param department
     * @param age
     * @return
     *     returns java.util.List<com.ifmo.serviceslab1maven.Employee>
     */
    @WebMethod(operationName = "FilterEmployees")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FilterEmployees", targetNamespace = "http://serviceslab1maven.ifmo.com/", className = "com.ifmo.serviceslab1maven.FilterEmployees")
    @ResponseWrapper(localName = "FilterEmployeesResponse", targetNamespace = "http://serviceslab1maven.ifmo.com/", className = "com.ifmo.serviceslab1maven.FilterEmployeesResponse")
    public List<Employee> filterEmployees(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "surname", targetNamespace = "")
        String surname,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "department", targetNamespace = "")
        int department);

}
